### PR TITLE
[WIP] New dev tools

### PR DESCRIPTION
**Pull request by danielribeiro**

### CODE REVIEW

**Comment by danielribeiro** [comment]
@mikelikespie What do we need to do to get this merged?

**Comment by dfed** [comment]
Ping @mikelikespie

**Comment by Derimagia** [comment]
I tested this on my own repo, and everything seems to be working well. Not sure how much others have tested. There were some merge conflicts that I needed to resolve.

**Comment by 3a4oT** [comment]
Any updates on this?

**Pull request closed without merging**
